name: Windows

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: [
          { sys: mingw64, cxx: g++, cc: gcc },
          { sys: clang64, cxx: clang++, cc: clang },
        ]
    name: Windows (${{ matrix.cxx }})
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
    - name: Setting up using ${{ matrix.cc }}
      run: "set CXX=${{ matrix.cxx }} & set CC=${{ matrix.cc }} & make setup"
      shell: cmd
    - name: Building with ${{ matrix.cxx }}
      run: "set CXX=${{ matrix.cxx }} & set CC=${{ matrix.cc }} & make build"
      shell: cmd
    - name: 'Export binary'
      uses: actions/upload-artifact@v3
      with:
          name: app.exe
          path: bin/windows/app.exe
    - name: "Final cleaning"
      run: make clean && make clean-lib
      shell: cmd
