name: Windows

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        sys:
        - mingw64
        - clang64
        compiler:
        - g++
        - clang++
    name: Windows (${{ matrix.compiler }})
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
    - name: Setting up
      run: "set CXX=${{ matrix.compiler }} & make setup"
      shell: cmd
    - name: Building with default compiler (G++/GCC)
      run: "set CXX=${{ matrix.compiler }} & make build"
      shell: cmd
    - name: 'Export binary'
      uses: actions/upload-artifact@v3
      with:
          name: app.exe
          path: bin/windows/app.exe
    - name: "Final cleaning"
      run: make clean && make clean-lib
      shell: cmd
